=== SAP/sailing-analytics/java/com.sap.sailing.xrr.resultimport/schema/sailingXRR_v1.3.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified">
<!--
	<xsd:include schemaLocation="http://datafeed.sailing.org/sailingXRR_isafextend.xsd"/>
-->
	<xsd:include schemaLocation="sailingXRR_isafextend.xsd"/>
	<xsd:simpleType name="CrewPosition">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="S">
				<xsd:annotation>
					<xsd:documentation>Skipper</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="C">
				<xsd:annotation>
					<xsd:documentation>Crew</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="EventType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Regatta"/>
			<xsd:enumeration value="RegattaSeries"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DivisionType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="FleetRace"/>
			<xsd:enumeration value="TeamRace"/>
			<xsd:enumeration value="MatchRace"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="MatchRaceEntry">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Port"/>
			<xsd:enumeration value="Starboard"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PersonGender">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Male">
				<xsd:annotation>
					<xsd:documentation>Male</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="Female">
				<xsd:annotation>
					<xsd:documentation>Female</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="EventGender">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Men">
				<xsd:annotation>
					<xsd:documentation>Men</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="Women">
				<xsd:annotation>
					<xsd:documentation>Women</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="Open">
				<xsd:annotation>
					<xsd:documentation>Open</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="Mixed">
				<xsd:annotation>
					<xsd:documentation>Mixed</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Person">
		<xsd:attribute name="PersonID" type="xsd:string" use="required"/>
		<xsd:attribute name="IFPersonID" type="xsd:string" use="required"/>
		<xsd:attribute name="FamilyName" type="xsd:string" use="required"/>
		<xsd:attribute name="GivenName" type="xsd:string" use="optional"/>
		<xsd:attribute name="NOC" type="IFNationCode" use="optional"/>
		<xsd:attribute name="Gender" type="PersonGender" use="optional"/>
		<xsd:attribute name="ClassificationGroup" type="IFCfcnGroup" use="optional"/>
		<xsd:attribute name="ClassificationStatus" type="IFCfcnStatus" use="optional"/>
		<xsd:attribute name="ClassificationExpiry" type="xsd:date" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="Crew">
		<xsd:attribute name="PersonID" type="xsd:string" use="required"/>
		<xsd:attribute name="Position" type="CrewPosition" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="Boat">
		<xsd:attribute name="BoatID" type="xsd:string" use="required"/>
		<xsd:attribute name="BoatName" type="xsd:string" use="optional"/>
		<xsd:attribute name="SailNumber" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="Division">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="SeriesResult" type="SeriesResult"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="RaceResult" type="RaceResult"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="TRRaceResult" type="TRRaceResult"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="TRSeriesResult" type="TRSeriesResult"/>
		</xsd:choice>
		<xsd:attribute default="FleetRace" name="Type" type="DivisionType" use="optional"/>
		<xsd:attribute name="DivisionID" type="xsd:string" use="required"/>
		<xsd:attribute name="IFDivisionID" type="xsd:string" use="optional"/>
		<xsd:attribute name="Title" type="xsd:string" use="required"/>
		<xsd:attribute name="IFClassID" type="IFClassCode" use="optional"/>
		<xsd:attribute name="Gender" type="EventGender" use="optional"/>
		<xsd:attribute name="Disabled" type="xsd:boolean" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="Team">
		<xsd:sequence>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="Crew" type="Crew"/>
		</xsd:sequence>
		<xsd:attribute name="TeamID" type="xsd:string" use="required"/>
		<xsd:attribute name="BoatID" type="xsd:string" use="required"/>
		<xsd:attribute name="NOC" type="IFNationCode" use="optional"/>
		<xsd:attribute name="TeamName" type="xsd:string" use="optional"/>
		<xsd:attribute name="Gender" type="EventGender" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="Race">
		<xsd:annotation>
			<xsd:documentation>
				very preliminary, info about a single race within a regatta
			</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="RaceID" type="xsd:string" use="required"/>
		<xsd:attribute name="RaceNumber" type="xsd:integer" use="required"/>
		<xsd:attribute name="RaceName" type="xsd:string" use="optional"/>
		<xsd:attribute name="RaceStartDate" type="xsd:date" use="optional"/>
		<xsd:attribute name="RaceStartTime" type="xsd:time" use="optional"/>
		<xsd:attribute name="RaceStatus" type="IFRaceStatus" use="optional"/>
		<xsd:attribute name="Stage" type="xsd:string" use="optional"/>
		<xsd:attribute name="Flight" type="xsd:string" use="optional"/>
		<xsd:attribute name="Match" type="xsd:string" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="RaceResult">
		<xsd:attribute name="RaceID" type="xsd:string" use="required"/>
		<xsd:attribute name="TeamID" type="xsd:string" use="required"/>
		<xsd:attribute name="BoatID" type="xsd:string" use="optional"/>
		<xsd:attribute name="RacePoints" type="xsd:decimal" use="required"/>
		<xsd:attribute name="RaceRank" type="xsd:positiveInteger" use="optional"/>
		<xsd:attribute default="false" name="Discard" type="xsd:boolean" use="optional"/>
		<xsd:attribute name="ScoreCode" type="IFBoatStatus" use="optional"/>
		<xsd:attribute name="Entry" type="MatchRaceEntry" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="SeriesResult">
		<xsd:attribute name="TeamID" type="xsd:string" use="required"/>
		<xsd:attribute name="NetPoints" type="xsd:decimal" use="optional"/>
		<xsd:attribute name="TotalPoints" type="xsd:decimal" use="optional"/>
		<xsd:attribute default="false" name="Tied" type="xsd:boolean" use="optional"/>
		<xsd:attribute name="Rank" type="xsd:positiveInteger" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="TRRaceResult">
		<xsd:attribute name="RaceID" type="xsd:string" use="required"/>
		<xsd:attribute name="NetPoints" type="xsd:decimal" use="required"/>
		<xsd:attribute name="TeamPoints" type="xsd:decimal" use="required"/>
		<xsd:attribute name="RaceRank" type="xsd:positiveInteger" use="optional"/>
	</xsd:complexType>
	<xsd:complexType name="TRSeriesResult">
		<xsd:attribute name="NetPoints" type="xsd:decimal" use="optional"/>
		<xsd:attribute name="TotalPoints" type="xsd:decimal" use="optional"/>
		<xsd:attribute default="false" name="Tied" type="xsd:boolean" use="optional"/>
		<xsd:attribute name="Rank" type="xsd:positiveInteger" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="EventRef">
		<xsd:attribute name="Value" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="RegattaSeriesResult">
		<xsd:choice maxOccurs="unbounded" minOccurs="1">
			<xsd:element name="EventID" type="EventRef"/>
		</xsd:choice>
		<xsd:attribute name="TeamID" type="xsd:string" use="optional"/>
		<xsd:attribute name="TotalPoints" type="xsd:decimal" use="required"/>
		<xsd:attribute name="Rank" type="xsd:positiveInteger" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="Event">
		<xsd:choice maxOccurs="unbounded" minOccurs="1">
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="Race" type="Race"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="Division" type="Division"/>
			<xsd:element maxOccurs="unbounded" minOccurs="0" name="RegattaSeriesResult" type="RegattaSeriesResult"/>
		</xsd:choice>
		<xsd:attribute name="EventID" type="xsd:string" use="required"/>
		<xsd:attribute name="IFEventID" type="xsd:string" use="optional"/>
		<xsd:attribute default="Regatta" name="Type" type="EventType" use="optional"/>
		<xsd:attribute name="Title" type="xsd:string" use="optional"/>
	</xsd:complexType>

	<xsd:complexType name="RegattaResults">
		<xsd:choice maxOccurs="unbounded" minOccurs="1">
			<xsd:element maxOccurs="unbounded" minOccurs="1" name="Person" type="Person"/>
			<xsd:element maxOccurs="unbounded" minOccurs="1" name="Boat" type="Boat"/>
			<xsd:element maxOccurs="unbounded" minOccurs="1" name="Team" type="Team"/>
			<xsd:element maxOccurs="unbounded" minOccurs="1" name="Event" type="Event"/>
		</xsd:choice>
		<xsd:attribute name="Date" type="xsd:date" use="required"/>
		<xsd:attribute name="Time" type="xsd:time" use="required"/>
		<xsd:attribute name="Type" type="xsd:string" use="required"/>
		<xsd:attribute name="Version" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:element name="SailingXRR" type="RegattaResults">
	</xsd:element>
</xsd:schema>

=== SAP/sailing-analytics/java/com.sap.sailing.sailwave.resultimport.test/resources/EYSEC 2012 - TEST ISAF XRR.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<SailingXRR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Date="20130626" Time="191929" Type="SailingXRR" Version="1.3" xsi:noNamespaceSchemaLocation="http://www.sailing.org/uploads/xml/sailingXRR_v1.3.xsd">
<Person FamilyName="Ruggiero" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Davide" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Anna" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Sofia" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Jakob" GivenName="" IFPersonID="GERJM44" PersonID="GERJM44" />
<Person FamilyName="Andreas" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Clara" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Arianna" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Frederik" GivenName="" IFPersonID="DENFJ4" PersonID="DENFJ4" />
<Person FamilyName="Oliver" GivenName="Markus" IFPersonID="" PersonID="" />
<Person FamilyName="Davide" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Francesco" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Pierre" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Eliot" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Beste" GivenName="" IFPersonID="TURBK13" PersonID="TURBK13" />
<Person FamilyName="Simay" GivenName="" IFPersonID="TURSA11" PersonID="TURSA11" />
<Person FamilyName="Niels" GivenName="" IFPersonID="DENND2" PersonID="DENND2" />
<Person FamilyName="Erik" GivenName="" IFPersonID="DENED1" PersonID="DENED1" />
<Person FamilyName="Sara" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Marek" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Lily" GivenName="" IFPersonID="GBRLS32" PersonID="GBRLS32" />
<Person FamilyName="Jemima" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Doga" GivenName="" IFPersonID="TURDS6" PersonID="TURDS6" />
<Person FamilyName="Ibrahim" GivenName="" IFPersonID="TURIB4" PersonID="TURIB4" />
<Person FamilyName="Mathilde" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Marine" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Alan" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Gray" GivenName="" IFPersonID="GBRAG57" PersonID="GBRAG57" />
<Person FamilyName="Stephanie" GivenName="" IFPersonID="GBRSO19" PersonID="GBRSO19" />
<Person FamilyName="Victoria" GivenName="" IFPersonID="GBRVP5" PersonID="GBRVP5" />
<Person FamilyName="Charlotte" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Thomas" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Rhos" GivenName="" IFPersonID="GBRRH84" PersonID="GBRRH84" />
<Person FamilyName="Benjamin" GivenName="" IFPersonID="GBRBH37" PersonID="GBRBH37" />
<Person FamilyName="Ellie" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Lucy" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Konrad" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Michal" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Simon" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Emile" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Martyna" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Karolina" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Filip" GivenName="" IFPersonID="DENFH5" PersonID="DENFH5" />
<Person FamilyName="Mathias" GivenName="" IFPersonID="DENMJ13" PersonID="DENMJ13" />
<Person FamilyName="Joakim" GivenName="" IFPersonID="DENJS20" PersonID="DENJS20" />
<Person FamilyName="Christopher" GivenName="" IFPersonID="DENCF4" PersonID="DENCF4" />
<Person FamilyName="Ludvig" GivenName="" IFPersonID="NORLJ4" PersonID="NORLJ4" />
<Person FamilyName="Føyen" GivenName="" IFPersonID="NORBW4" PersonID="NORBW4" />
<Person FamilyName="Tobias" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Casper" GivenName="" IFPersonID="DENCL8" PersonID="DENCL8" />
<Person FamilyName="Edoardo" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Alessandro" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Anisah" GivenName="" IFPersonID="GERAS55" PersonID="GERAS55" />
<Person FamilyName="Gesa" GivenName="" IFPersonID="GERGB12" PersonID="GERGB12" />
<Person FamilyName="Ole" GivenName="" IFPersonID="GEROK3" PersonID="GEROK3" />
<Person FamilyName="Niclas" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Ottavia" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Davide" GivenName="" IFPersonID="" PersonID="" />
<Person FamilyName="Alloway" GivenName="" IFPersonID="GBRWA6" PersonID="GBRWA6" />
<Person FamilyName="Matthew" GivenName="" IFPersonID="GBRMV8" PersonID="GBRMV8" />
<Boat BoatID="1" SailNumber="ITA 54173" />
<Boat BoatID="7" SailNumber="ITA 54278" />
<Boat BoatID="13" SailNumber="GER 2020" />
<Boat BoatID="8" SailNumber="ITA 54543" />
<Boat BoatID="14" SailNumber="DEN 1896" />
<Boat BoatID="2" SailNumber="ITA 54552" />
<Boat BoatID="3" SailNumber="FRA 53493" />
<Boat BoatID="9" SailNumber="TUR 54284" />
<Boat BoatID="15" SailNumber="DEN 935" />
<Boat BoatID="16" SailNumber="POL 1756" />
<Boat BoatID="10" SailNumber="GBR 53966" />
<Boat BoatID="4" SailNumber="TUR 54288" />
<Boat BoatID="5" SailNumber="GBR 54364" />
<Boat BoatID="11" SailNumber="FRA 54520" />
<Boat BoatID="17" SailNumber="GBR 1960" />
<Boat BoatID="18" SailNumber="GER 1914" />
<Boat BoatID="6" SailNumber="GBR 53703" />
<Boat BoatID="12" SailNumber="GBR 52674" />
<Boat BoatID="19" SailNumber="POL 1758" />
<Boat BoatID="20" SailNumber="FRA 1747" />
<Boat BoatID="21" SailNumber="POL 1772" />
<Boat BoatID="22" SailNumber="DEN 1553" />
<Boat BoatID="23" SailNumber="DEN 1732" />
<Boat BoatID="24" SailNumber="NOR 1961" />
<Boat BoatID="25" SailNumber="DEN 1776" />
<Boat BoatID="26" SailNumber="ITA 1658" />
<Boat BoatID="27" SailNumber="GER 1970" />
<Boat BoatID="28" SailNumber="GER 1862" />
<Boat BoatID="29" SailNumber="ITA 1340" />
<Boat BoatID="30" SailNumber="GBR 900" />
<Team NOC="ITA" TeamID="ITAITA 54173" BoatID="1" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="ITA" TeamID="ITAITA 54278" BoatID="7" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="GER" TeamID="GERGER 2020" BoatID="13" >
<Crew PersonID="GERJM44" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="ITA" TeamID="ITAITA 54543" BoatID="8" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="DEN" TeamID="DENDEN 1896" BoatID="14" >
<Crew PersonID="DENFJ4" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="ITA" TeamID="ITAITA 54552" BoatID="2" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="FRA" TeamID="FRAFRA 53493" BoatID="3" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="TUR" TeamID="TURTUR 54284" BoatID="9" >
<Crew PersonID="TURBK13" Position="C" />
<Crew PersonID="TURSA11" Position="S" />
</Team>
<Team NOC="DEN" TeamID="DENDEN 935" BoatID="15" >
<Crew PersonID="DENND2" Position="S" />
<Crew PersonID="DENED1" Position="C" />
</Team>
<Team NOC="POL" TeamID="POLPOL 1756" BoatID="16" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="GBR" TeamID="GBRGBR 53966" BoatID="10" >
<Crew PersonID="GBRLS32" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="TUR" TeamID="TURTUR 54288" BoatID="4" >
<Crew PersonID="TURDS6" Position="S" />
<Crew PersonID="TURIB4" Position="C" />
</Team>
<Team NOC="GBR" TeamID="GBRGBR 54364" BoatID="5" >
<Crew PersonID="" Position="S" />
<Crew PersonID="GBRAG57" Position="C" />
</Team>
<Team NOC="FRA" TeamID="FRAFRA 54520" BoatID="11" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="GBR" TeamID="GBRGBR 1960" BoatID="17" >
<Crew PersonID="GBRSO19" Position="S" />
<Crew PersonID="GBRVP5" Position="C" />
</Team>
<Team NOC="GER" TeamID="GERGER 1914" BoatID="18" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="GBR" TeamID="GBRGBR 53703" BoatID="6" >
<Crew PersonID="GBRRH84" Position="S" />
<Crew PersonID="GBRBH37" Position="C" />
</Team>
<Team NOC="GBR" TeamID="GBRGBR 52674" BoatID="12" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="POL" TeamID="POLPOL 1758" BoatID="19" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="FRA" TeamID="FRAFRA 1747" BoatID="20" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="POL" TeamID="POLPOL 1772" BoatID="21" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="DEN" TeamID="DENDEN 1553" BoatID="22" >
<Crew PersonID="DENFH5" Position="S" />
<Crew PersonID="DENMJ13" Position="C" />
</Team>
<Team NOC="DEN" TeamID="DENDEN 1732" BoatID="23" >
<Crew PersonID="DENJS20" Position="S" />
<Crew PersonID="DENCF4" Position="C" />
</Team>
<Team NOC="NOR" TeamID="NORNOR 1961" BoatID="24" >
<Crew PersonID="NORLJ4" Position="C" />
<Crew PersonID="NORBW4" Position="S" />
</Team>
<Team NOC="DEN" TeamID="DENDEN 1776" BoatID="25" >
<Crew PersonID="" Position="S" />
<Crew PersonID="DENCL8" Position="C" />
</Team>
<Team NOC="ITA" TeamID="ITAITA 1658" BoatID="26" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="GER" TeamID="GERGER 1970" BoatID="27" >
<Crew PersonID="GERAS55" Position="C" />
<Crew PersonID="GERGB12" Position="S" />
</Team>
<Team NOC="GER" TeamID="GERGER 1862" BoatID="28" >
<Crew PersonID="GEROK3" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="ITA" TeamID="ITAITA 1340" BoatID="29" >
<Crew PersonID="" Position="S" />
<Crew PersonID="" Position="C" />
</Team>
<Team NOC="GBR" TeamID="GBRGBR 900" BoatID="30" >
